name: Render documents with rmarkdown-action
on: [push]
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: richarddmorey/rmarkdown-action@v1.2
        with:
          input_file: text/apa_paper/Morey2026_decline_effects.Rmd
          output_format: pdf_document 
